name: Create VM

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
      with:
        terraform_version: 0.13.5
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
    
    - run: terraform init
    - run: terraform apply terraform apply -auto-approve -var "MY_VARIABLE=${{ secrets.GCP_SERVICE_ACCESS_TOKEN }}" 

